# Errors and Exceptions


- Error is "Problem"
- Exception is "Condition"



## 测试

代码准备

```js
const path = require('path');
const fs = require('fs');

const files = ['.bashrc', '.vimrc'];

files.forEach(file => {
    const filePath = path.resolve(process.env.HOME, file);
    const data = fs.readFileSync(filePath);
    console.log('File data is', data);
})
```

**触发Error**


```js
// 写个不存在的文件名

const files = ['.bashrc', 'sdfe', '.vimrc'];
```

此时运行就报错了

**try捕获异常**

try catch

```js
const path = require('path');
const fs = require('fs');

const files = ['.bashrc', 'asefa', '.vimrc'];

files.forEach(file => {
    try {
        const filePath = path.resolve(process.env.HOME, file);
        const data = fs.readFileSync(filePath);
        console.log('File data is', data);
    } catch(error) {
        console.log('File not found');
    }

})
```

**throw 抛出异常**

```js
const path = require('path');
const fs = require('fs');

const files = ['.bashrc', 'asefa', '.vimrc'];

files.forEach(file => {
    try {
        const filePath = path.resolve(process.env.HOME, file);
        const data = fs.readFileSync(filePath);
        console.log('File data is', data);
    } catch(err) {
        if (err.code === 'ENOENT') {
            console.log('File not found');
        }
        else {
            throw err;
        }
    }
})
```
