# errno.h和错误号

几乎所有的c标准库函数出错时，都会有相应的出错原因，c标准库会使用各种错误号（整数）来代表相应的错误，这些错误号定义在了`errno.h`中。

## errno.h

```
#ifndef _ERRNO_H_
#define _ERRNO_H_

#define EPERM               1       //Operation not permitted(权限问题，不允许操作)
...
#define EINVAL              22      //Invalid argument（无效参数）
...
#define EROFS               30      //Read-only file system（文件是只读的）
...
#define ENAMETOOLONG        38      //Filename too long (91 in Cyg?)(文件名太长，最多只允许91字符)
...

extern int errno;           //存放错误号的全局变量，如果没有任何函数出错，里面默认就是0

...

#endif
```

- 当被调用的库函数出错时，就会自动将错误号设置到全局变量`errno`中
- 调用`strerror`可以将`errno`中的值翻译成对应的字符串说明。


## 使用strerror打印错误信息

```
#include <stdio.h>  //fprintf所需的.h
#include <string.h> //strerror所需的.h
#include <errno.h>  //全局变量errno所在的.h
#include <stdlib.h> //exit函数所需的.h

int main(void){
    FILE *p = fopen("./file", "t");
    if(NULL == p){
        fprintf(stderr, "fopen error: %s\n", strerror(errno));
        exit(-1);   //直接终止进程
    }

    return 0;
}

//输出结果：fopen error: Invalid argument
```

- `strerror`会自动取出`errno`的中的错误号并将`22`翻译为`Invalid argument`，并且将字符串指针返回
- 利用这个返回字符串指针，就能通过`%s`打印出`Invalid argument`，以提示出了什么错误。

## 使用perror打印错误信息

```
#include <stdio.h>
#include <stdlib.h>

int main(void){
    FILE *p = fopen("./file", "t");
    if(NULL == p){
        perror("fopen error");
        exit(-1);
    }
    return 0;
}
```

- `perror`函数由`stdio.h`提供，并且不用包含`string.h`和`errno.h`
- 可见`perror`更佳简洁

## 使用函数打印错误信息

```
#include <stdio.h>
#include <stdlib.h>

void print_error(char *str){

    fprintf(stderr, "File %s, Line %d, Function %s error\n", __FILE__, __LINE__, str);
    perror("error reason");
    exit(-1);
}


int fun(int **p, int size){
    *p = malloc(size);
    if(NULL == *p) print_error("malloc");
}

int main(void){
    int ret = 0;
    int *p = 0;
    long long int size = sizeof(int) * 400000000000000000000000;

    ret = fun(&p, size);

    return 0;
}

//输出结果：error reason: Cannot allocate memory
```

## 宏的方式

```
#include <stdio.h>
#include <stdlib.h>

#define praint_error(str) \
    do{\
        fprintf(stderr, "File %s, Line %d, Function %s error\n", __FILE__, __LINE__, str);\
        perror("error reason");\
        exit(-1);\
    }while(0);

int fun(int **p, int size){
    *p = malloc(size);
    if(NULL == *p) print_error("malloc");
}

int main(void){
    int ret = 0;
    int *p = 0;
    long long int size = sizeof(int) * 400000000000000000000000;

    ret = fun(&p, size);

    return 0;
}
```

## 有关报错函数

1. 并不是所有函数都需要报错处理，只需要对重要的关键的函数进行报错处理
2. 自己写的函数，重要函数也要返回`NULL`或者`-1`，并进行出错处理
3. 当函数出错后，一般有两种处理方式：
   - 调用`exit()`结束整个进程
   - 调用`return`返回上一级，比如返回`-1`
4. 如果有需要的话，还需对错误进行相应处理
